#!/bin/bash

# go to root
cd

# disable ipv6
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local

# install wget and curl
apt-get update;apt-get -y install wget curl;

# set time GMT +7
ln -fs /usr/share/zoneinfo/Asia/Bangkok /etc/localtime

# set locale
sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config
service ssh restart

# set repo
wget -O /etc/apt/sources.list "https://raw.githubusercontent.com/kunphiphit/debian/config/sources.list.debian8"
wget "http://www.dotdeb.org/dotdeb.gpg"
cat dotdeb.gpg | apt-key add -;rm dotdeb.gpg

# remove unused
apt-get -y --purge remove samba*;
apt-get -y --purge remove apache2*;
apt-get -y --purge remove sendmail*;
apt-get -y --purge remove bind9*;

# update
apt-get update; apt-get -y upgrade;

# install webserver
apt-get -y install nginx php5-fpm php5-cli

# install essential package
apt-get -y install nmap nano iptables traceroute sysv-rc-conf dnsutils bc nethogs openvpn openssl ca-certificates vnstat less screen psmisc apt-file whois ptunnel ngrep git zsh unzip unrar rsyslog debsums rkhunter
apt-get -y install build-essential

# disable exim
service exim4 stop
sysv-rc-conf exim4 off

# update apt-file
apt-file update

# setting vnstat
vnstat -u -i eth0
service vnstat restart

# install screenfetch
cd
wget https://raw.githubusercontent.com/kunphiphit/debian/config/screenfetch-dev
mv screenfetch-dev /usr/bin/screenfetch
chmod +x /usr/bin/screenfetch
echo "clear" >> .profile
echo "screenfetch" >> .profile

# install webserver
cd
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
wget -O /etc/nginx/nginx.conf "https://raw.githubusercontent.com/kunphiphit/debian/config/nginx.conf"
mkdir -p /home/vps/public_html
echo "<?php phpinfo(); ?>" > /home/vps/public_html/info.php
wget -O /etc/nginx/conf.d/vps.conf "https://raw.githubusercontent.com/kunphiphit/debian/config/vps.conf"
sed -i 's/listen = \/var\/run\/php5-fpm.sock/listen = 127.0.0.1:9000/g' /etc/php5/fpm/pool.d/www.conf
service php5-fpm restart
service nginx restart

# install openvpn
wget -O /etc/openvpn/openvpn.tar "https://raw.githubusercontent.com/kunphiphit/debian/config/openvpn-debian.tar"
cd /etc/openvpn/
tar xf openvpn.tar
wget -O /etc/openvpn/1194.conf "https://raw.githubusercontent.com/kunphiphit/debian/config/1194.conf"

MYIP1=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
if [[ "$MYIP1" = "" ]]; then
		MYIP1=$(wget -4qO- "http://whatismyip.akamai.com/")
        MYIP2="s/xxxxxxxx/$MYIP1/g";
fi
	sed -i '/\<net.ipv4.ip_forward\>/c\net.ipv4.ip_forward=1' /etc/sysctl.conf
	if ! grep -q "\<net.ipv4.ip_forward\>" /etc/sysctl.conf; then
		echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
	fi
	echo 1 > /proc/sys/net/ipv4/ip_forward
	if pgrep firewalld; then
		firewall-cmd --zone=public --add-port=1194/tcp
		firewall-cmd --zone=trusted --add-source=10.8.0.0/24
		firewall-cmd --permanent --zone=public --add-port=1194/tcp
		firewall-cmd --permanent --zone=trusted --add-source=10.8.0.0/24
		firewall-cmd --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to xxxxxxxx
		firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to xxxxxxxx
	else
		if [[ "$OS" = 'debian' && ! -e $RCLOCAL ]]; then
			echo '#!/bin/sh -e
exit 0' > $RCLOCAL
		fi
		chmod +x $RCLOCAL
		iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to xxxxxxxx
		sed -i "1 a\iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to xxxxxxxx" $RCLOCAL
		if iptables -L -n | grep -qE '^(REJECT|DROP)'; then
			iptables -I INPUT -p tcp --dport 1194 -j ACCEPT
			iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT
			iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
			sed -i "1 a\iptables -I INPUT -p tcp --dport 1194 -j ACCEPT" $RCLOCAL
			sed -i "1 a\iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT" $RCLOCAL
			sed -i "1 a\iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT" $RCLOCAL
		fi
	if [[ "$OS" = 'debian' ]]; then
		if pgrep systemd-journal; then
			systemctl restart openvpn@server.service
		else
			/etc/init.d/openvpn restart
		fi
	else
		if pgrep systemd-journal; then
			systemctl restart openvpn@server.service
			systemctl enable openvpn@server.service
		else
			service openvpn restart
			chkconfig openvpn on
		fi
	fi
	EXTERNALIP=$(wget -4qO- "http://whatismyip.akamai.com/")
	if [[ "$MYIP1" != "$EXTERNALIP" ]]; then
		echo ""
		read -p "External IP: " -e USEREXTERNALIP
		if [[ "$USEREXTERNALIP" != "" ]]; then
			MYIP1="$USEREXTERNALIP"
		fi
	fi
MYIP=`curl -s ifconfig.me`;
MYIP2="s/xxxxxxxxx/$MYIP/g";
sed -i $MYIP2 /etc/iptables.up.rules;
iptables-restore < /etc/iptables.up.rules
service openvpn restart

# configure openvpn client config
cd /etc/openvpn/
wget -O /etc/openvpn/client.conf "https://raw.githubusercontent.com/kunphiphit/debian/config/client.conf"
cp client.conf /home/vps/public_html/client.ovpn
echo "<ca>" >> /home/vps/public_html/client.ovpn
cat /keys/ca.crt >> /home/vps/public_html/client.ovpn
echo "</ca>" >> /home/vps/public_html/client.ovpn
sed -i $MYIP2 /etc/openvpn/client.conf;
cd
# install badvpn
wget -O /usr/bin/badvpn-udpgw "https://raw.githubusercontent.com/kunphiphit/debian/config/badvpn-udpgw"
sed -i '$ i\screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300' /etc/rc.local
chmod +x /usr/bin/badvpn-udpgw
screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300

# setting port ssh
sed -i '/Port 22/a Port 22' /etc/ssh/sshd_config
sed -i 's/Port 22/Port  22/g' /etc/ssh/sshd_config
service ssh restart

# install dropbear
apt-get -y install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=143/g' /etc/default/dropbear
sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 109 -p 110"/g' /etc/default/dropbear
echo "/bin/nologin" >> /etc/shells
service ssh restart
service dropbear restart

# install vnstat gui
cd
wget http://www.sqweek.com/sqweek/files/vnstat_php_frontend-1.5.1.tar.gz
tar xf vnstat_php_frontend-1.5.1.tar.gz vnstat
rm vnstat_php_frontend-1.5.1.tar.gz
mv vnstat /home/vps/public_html
cd /home/vps/public_html
sed -i 's/eth0/eth0/g' config.php
sed -i "s/\$iface_list = array('eth0', 'sixxs');/\$iface_list = array('eth0');/g" config.php
sed -i "s/\$language = 'nl';/\$language = 'en';/g" config.php
sed -i 's/Internal/Internet/g' config.php
sed -i '/SixXS IPv6/d' config.php
cd

# install squid3
apt-get -y install squid3
wget -O /etc/squid3/squid.conf "https://raw.githubusercontent.com/kunphiphit/debian/config/squid3.conf"
sed -i $MYIP2 /etc/squid3/squid.conf;
service squid3 restart

# install webmin
cd
wget "https://raw.githubusercontent.com/kunphiphit/debian/config/webmin_1.880_all.deb"
dpkg --install webmin_1.880_all.deb;
apt-get -y install perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl apt-show-versions python;
wget http://www.webmin.com/jcameron-key.asc
apt-key add jcameron-key.asc;
rm -rf jcameron-key.asc;
apt-get update
apt-get -y install webmin;
rm -rf webmin_1.880_all.deb
apt-get -f install -y;
service webmin restart
service vnstat restart

# download script
cd /usr/bin
wget -O menu "
https://raw.githubusercontent.com/kunphiphit/debian/config/menu.sh"
wget -O 1 "
https://raw.githubusercontent.com/kunphiphit/debian/config/adduser.sh"
wget -O 2 "
https://raw.githubusercontent.com/kunphiphit/debian/config/delete.sh"
wget -O 3 "
https://raw.githubusercontent.com/kunphiphit/debian/config/deleteauto.sh"
wget -O 4 "
https://raw.githubusercontent.com/kunphiphit/debian/config/viewuser.sh"
wget -O 5 "
https://raw.githubusercontent.com/kunphiphit/debian/config/restart.sh"
wget -O 6 "
https://raw.githubusercontent.com/kunphiphit/debian/config/speedtest.py"
wget -O 7 "
https://raw.githubusercontent.com/kunphiphit/debian/config/online.sh"
wget -O 8 "
https://raw.githubusercontent.com/kunphiphit/debian/config/viewlogin.sh"
wget -O 9 "
https://raw.githubusercontent.com/kunphiphit/debian/config/aboutsystem.sh"
wget -O 10 "
https://raw.githubusercontent.com/kunphiphit/debian/config/about.sh"
wget -O 11 "
https://raw.githubusercontent.com/kunphiphit/debian/config/credithttp.sh"
wget -O 12 "
https://raw.githubusercontent.com/kunphiphit/debian/config/timereboot.sh"
wget -O 13 "
https://raw.githubusercontent.com/kunphiphit/debian/config/backup"
wget -O 14 "
https://raw.githubusercontent.com/kunphiphit/debian/config/bandwidth"

# finalisasi
chown -R www-data:www-data /home/vps/public_html
service nginx start
service php-fpm start
service vnstat restart
service openvpn restart
service ssh restart
service dropbear restart
service squid3 restart
service webmin restart

# info
clear
echo "AUTOSCRIPT | @DEBIAN| 7-8 | X64" | tee log-install.txt
echo "===============================================" | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Service"  | tee -a log-install.txt
echo "-------"  | tee -a log-install.txt
echo "OpenVPN  : TCP 1194 (client config : http://$MYIP/client.ovpn)"  | tee -a log-install.txt
echo "OpenSSH  : 22 "  | tee -a log-install.txt
echo "Dropbear : 109, 110, 143"  | tee -a log-install.txt
echo "Squid3   : 8080 (limit to IP SSH)"  | tee -a log-install.txt
echo "badvpn   : badvpn-udpgw port 7300"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt


echo "Script"  | tee -a log-install.txt
echo "------"  | tee -a log-install.txt


echo ""  | tee -a log-install.txt
echo "---------------"  | tee -a log-install.txt

echo ""  | tee -a log-install.txt
echo "----------"  | tee -a log-install.txt
echo "Webmin   : https://$MYIP:10000/"  | tee -a log-install.txt
echo "vnstat   : http://$MYIP/"  | tee -a log-install.txt
echo "Timezone : Asia/Bangkok"  | tee -a log-install.txt
echo "IPv6     : [off]"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Log Installation --> /root/log-install.txt"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "REBOOT VPS !"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "==============================================="  | tee -a log-install.txt
